version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"  # Corrigido para porta 80 padrão do nginx
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  api1: &api
    image: pedra0x910/payment-quarkus:latest
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/rinha
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    hostname: api1
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "140MB"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "8081:8080"

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true