services:
  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20mb"
  api01:
    image: pedra0x910/payment-quarkus:latest
    container_name: api01
    user: root
    networks:
      - backend
      - payment-processor
    environment:
      DB_USERNAME: rinha
      DB_PASSWORD: rinha123
      DB_HOST: jdbc:postgresql://postgres:5432/rinha
      DEFAULT_URL: http://payment-processor-default:8080
      FALLBACK_URL: http://payment-processor-fallback:8080
      JAVA_OPTIONS: "-Xlog:gc*,heap+usage=debug:stdout"
    volumes:
        - ./logs/api01:/tmp
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "140MB"
  api02:
    image: pedra0x910/payment-quarkus:latest
    container_name: api02
    user: root
    networks:
      - backend
      - payment-processor
    environment:
      DB_USERNAME: rinha
      DB_PASSWORD: rinha123
      DB_HOST: jdbc:postgresql://postgres:5432/rinha
      DEFAULT_URL: http://payment-processor-default:8080
      FALLBACK_URL: http://payment-processor-fallback:8080
      JAVA_OPTIONS: "-Xlog:gc*,heap+usage=debug:stdout"
    volumes:
        - ./logs/api01:/tmp
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "140MB"

  postgres:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinha
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/db/migration/V1__create_paymentRequest_table.sql:/docker-entrypoint-initdb.d/V1__create_paymentRequest_table.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true