version: '3.8'

services:
  quarkus-app-1:
    image: pedra0x910/payment-quarkus:latest
    ports:
      - "10001:8080"
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_HTTP_HOST: 0.0.0.0
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://payment-processor-default-db:5432/rinha
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    networks:
      - payment-processor
    depends_on:
      payment-processor-default-db:
        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          cpus: "0.75"
#          memory: "256MB"

  quarkus-app-2:
    image: pedra0x910/payment-quarkus:latest
    ports:
      - "10002:8080"
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_HTTP_HOST: 0.0.0.0
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://payment-processor-default-db:5432/rinha
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    networks:
      - payment-processor
    depends_on:
      payment-processor-default-db:
        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          cpus: "0.75"
#          memory: "256MB"

  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - payment-processor
    depends_on:
      - quarkus-app-1
      - quarkus-app-2
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "128MB"

networks:
  payment-processor:
    external: true