version: "3.9"

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    command: [ "nginx", "-g", "daemon off;" ]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"
    networks:
      - backend

  api1: &api
    image: pedra0x910/payment-quarkus:latest
    hostname: api1
    container_name: api1
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://payment-processor-fallback-db/rinha
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"

  api2:
    <<: *api
    hostname: api2
    container_name: api2
    ports:
      - "8081:8080"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true