version: "3.8"  # Remove a warning sobre 'version' obsoleta

services:
  # Banco de dados padrão (default)
  payment-processor-db-1:
    image: postgres:17-alpine
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db
    ports:
      - "54321:5432"  # Mapeia 54321 na sua máquina para 5432 do container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - ./V1__create_paymentRequest_table.sql:/docker-entrypoint-initdb.d/V1__create_paymentRequest_table.sql
    networks:
      - payment-processor
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

  # Banco de dados fallback
  payment-processor-db-2:
    image: postgres:17-alpine
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

  # App padrão (default)
  quarkus-app-1:
    image: quarkus/appquarkus-jvm  # Se essa imagem estiver no DockerHub, OK
    container_name: quarkus-app-1
    hostname: quarkus-app-1
    ports:
      - "9999:8080"   # Mapeia 8080 do container para 9999 da sua máquina
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://payment-processor-default-db:5432/rinha
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      DEFAULT_PROCESSOR_URL: http://payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: http://payment-processor-fallback:8080
    networks:
      - payment-processor
    depends_on:
       payment-processor-db-1:
          condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "175MB"

  # App fallback
  quarkus-app-2:
    image: quarkus/appquarkus-jvm
    container_name: quarkus-app-2
    hostname: quarkus-app-2
    ports:
      - "10000:8080"  # Use uma porta diferente pra poder acessar separadamente
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://payment-processor-fallback-db:5432/rinha
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      DEFAULT_PROCESSOR_URL: http://payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: http://payment-processor-fallback:8080
    networks:
      - payment-processor
    depends_on:
      - payment-processor-db-2
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "175MB"

  # Serviços Payment Processor (template de serviço)
  payment-processor-1:
    image: zanfranceschi/payment-processor:amd64-20250707101540
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      TRANSACTION_FEE: 0.05
      RATE_LIMIT_SECONDS: 5
      INITIAL_TOKEN: 123
      DB_CONNECTION_STRING: Host=payment-processor-default-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - "8001:8080"
    depends_on:
      - payment-processor-db-1
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

  payment-processor-2:
    image: zanfranceschi/payment-processor:amd64-20250707101540
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      TRANSACTION_FEE: 0.15
      RATE_LIMIT_SECONDS: 5
      INITIAL_TOKEN: 123
      DB_CONNECTION_STRING: Host=payment-processor-fallback-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - "8002:8080"
    depends_on:
      - payment-processor-db-2
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

networks:
  payment-processor:
    driver: bridge
